New RPC Methods
a16z/helios pull request #142
Opened 2022-12-13 20:38 UTC by giovannivignone

# Overview
Implementation of the `eth_getBlockTransactionCountByHash` and `eth_getBlockTransactionCountByNumber` RPC methods

## Changes
- Additional methods in node.rs and rpc.rs in the client
- Abstraction of fetching payload logic into a function called get_payload_by_hash in node.rs
- Change from infura -> alchemy in example as recommended RPC url

## ToDo
- [ ] Adjust rpc.md 
- [ ] Add methods to the client.rs file?

2022-12-13 23:10 UTC, ncitron requested changes
Looks pretty good. Just have a couple of minor changes.

Also don't worry about the benchmark ci failing. This is because you are opening from a fork, which doesn't have access to the RPC url secret in this repo. I'll think of a way to handle this in the future.

2022-12-13 23:10 UTC, ncitron commented on client/src/client.rs
> +    pub async fn get_block_transaction_count_by_hash(&self, hash: &Vec<u8>) -> Result<U256> {
Can we have both of these functions just return `u64`. They are easier to work with, and it is impossible to have a block fill enough transactions to overflow this. Same goes for these functions in `Node`.

2022-12-13 23:17 UTC, giovannivignone commented on client/src/client.rs
> +    pub async fn get_transaction_count(&self, address: &Address, block: BlockTag) -> Result<u64> {
This makes total sense. I was hoping you would comment on this as I wasn't sure it if was a good idea to introduce the change. Thank you will remove

2022-12-14 00:19 UTC, ncitron approved these changes
LGTM

2022-12-14 00:19 UTC, merged