eth_feeHistory Implementation
a16z/helios pull request #204
Opened 2023-03-09 15:14 UTC by SFYLL

Implement eth_feeHistory as requested in [#200](https://github.com/a16z/helios/issues/200) .

Veracity check on public RPC response done by comparing the response's base fee per gas with the local view provided by the `ExecutionPayload` object. This approach has two main corollaries:

- We take an optimistic view by assuming that if the response's base fee per block are correct, so are the rewards and gas ratios. Obviously, that's a subject for conversation;
- The `get_fee_history` in `execution/src/execution.rs`function checks the parameters and discards blocks that are not stored (and as such "validated") in `ExecutionPayload`. That makes returned values slightly less deterministic than one might have hoped, but seem in line with [Alchemy's](https://docs.alchemy.com/reference/eth-feehistory).

Given that the most insightful test were done by impersonating the user, i.e. putting in place integration tests, these were implemented in a new directory `tests/`.

Please note that this is my first PR into a public project + first time coding in Rust. So feel free to go heavy on the changes !

2023-03-09 19:25 UTC, ncitron commented
This is a good start. I do however think that we shouldn't trust the rest of response given that just part of it is provably correct. You can imagine attacks where an RPC sends correct base fees, but wildly high priority fees to trick Helios users into sending transactions with a high priority fee. They could then auction that artificially valuable transaction off to a miner using something like flashbots.

We should however be able to implement this method without needing any trust at all. Since Helios has past`ExecutionPayload`s, we can already get the base fees that we need. We also have the transaction list as a member of each `ExecutionPayload`, which we can use to decode the priority fees paid out in that block. With that list of priority fees, and a bit of math to figure out percentiles, we should be able to return a response with zero trust in the rpc.

Does this strategy make sense?

2023-03-10 16:08 UTC, SFYLL commented
Hey guys,

Tried my best but unfortunately computing the reward parameters ourselves has quite some overhead (can push on another branch if needed, just let me know). As can be seen with [reth](https://github.com/paradigmxyz/reth/blob/ea11461126229a75532bc96d97e615d3b47ea343/crates/rpc/rpc/src/eth/api/server.rs#LL290C33-L290C34), some client actually don't give an answer for this parameter. 

I tried though, and unfortunately amount of request quickly starts going out of hand. Indeed, you need the gas_used parameter per transaction to accumulate it until you reach the gas_used percentile, at which point you can return the gas paid for that specific transaction. Ultimately, what that means is that you need to get the receipt for every transaction in each block queried as there is no other way to get the gas used (practical way at least, not planning to track opcode raised for that endpoint 😬 ) ...

If there was a way to prove that the content was correct without querying it ourselves (wink wink zero-knowledge proof), it would make getting that list possible. Maybe we can follow reth for now and re-assess later on?

2023-03-10 16:09 UTC, refcell requested changes
Some minor changes requested. Overall, very nice work!

2023-03-10 16:09 UTC, refcell commented on execution/src/execution.rs
> +        let helios_oldest_block = *payloads.first_key_value().unwrap().0;
Unwraps will cause the program to panic (abort in release mode) - we should gracefully return an error here instead.

Example:

```suggestion
        let helios_latest_block = *payloads.last_key_value();
        let helios_latest_block = helios_latest_block.ok_or(BlockNotFoundError::new(BlockTag::Latest))?.0;
        let helios_oldest_block = *payloads.first_key_value();
        let helios_oldest_block = helios_oldest_block.ok_or(BlockNotFoundError::new(BlockTag::Number(0)))?.0;
```

(I would also allow `BlockNotFoundError` to accept an optional `BlockTag` so we can construct an error without knowing the actual block)

2023-03-10 16:09 UTC, refcell commented on execution/src/execution.rs
> +            return Ok(None);
I would return an error here personally - the end consumer should know if their request is out of the block range.

2023-03-10 16:09 UTC, refcell commented on execution/src/execution.rs
> +            let payload = payload.unwrap();
ibid. Gracefully handle error/panic here.

2023-03-10 17:48 UTC, refcell commented on execution/src/errors.rs
> +    EmptyExecutionPayload(),
nice!

2023-03-10 18:12 UTC, refcell approved these changes
Very nice!

2023-03-10 18:19 UTC, refcell commented
Hey @SFYLL, merging into a fee_history branch in the `a16z/helios` repo so we can resolve these formatting and api key issues locally :)

2023-03-10 18:19 UTC, merged