feat: add eth_getBlobBaseFee
a16z/helios pull request #452
Opened 2024-11-26 12:12 UTC by varun-doshi

Ref #200 

Added `eth_blobBaseFee`

2024-11-27 11:31 UTC, eshaan7 commented on core/src/client/rpc.rs
> +    #[method(name = "getBlobBaseFee")]
As per the [spec](https://ethereum.github.io/execution-apis/api-documentation/), it is `eth_blobBaseFee` so the `get` is not required.

2024-11-29 16:18 UTC, ncitron requested changes
Also there are some clippy and fmt errors introduced here related to unused imports.

2024-12-03 08:44 UTC, eshaan7 commented
nit: need to update method name in PR title as well.

2024-12-03 21:47 UTC, ncitron commented on core/src/client/rpc.rs
> +    #[method(name = "getBlobBaseFee")]
```suggestion
    #[method(name = "blobBaseFee")]
```

2024-12-03 21:53 UTC, merged